/* ------------------------------------------------------------------ */
/*  Presentation content — markdown-based, editable via Settings       */
/* ------------------------------------------------------------------ */

const STORAGE_KEY = 'jj-presentation-content';

/* ------------------------------------------------------------------ */
/*  Default markdown                                                    */
/* ------------------------------------------------------------------ */

export const defaultMarkdown = `---title---
# Job Journal
## From Career Chaos to Corpus-Driven Clarity
A case study in building what you need
Don Hogan | February 2026

---brutal-math---
# The Best Practice That Breaks You
Fully tailored resumes are the gold standard. Here's what that actually costs.
- **2-3 hours per application**: To research the role, map your experience, rewrite bullets, reformat, and proofread. That's the "best practice."
- **12 minutes to rejection**: Average time before ATS or recruiter screen filters you out. Before a human ever reads it.
- **Repeat 50-100 times**: The average job search requires dozens of applications. Do the math on 150+ hours of customization.
> You pour yourself into every application. An algorithm decides your fate before anyone reads your name.

---emotional-cycle---
# The Real Cost
It's not just time. It's energy.
Find posting, Get excited, Tailor for 3 hours, Submit, Rejected in 12 min
*This isn't a process problem. It's a human problem.*

---knowledge-exists---
# You Already Know Your Stories
We know our strengths, our stories, our impact. The knowledge is already in our heads.
The problem isn't content — it's that we re-derive it from scratch every single time.
- **Today: Start from Zero**: Copy-paste from old resumes. Try to remember what you did 3 years ago. Google yourself to find achievements you've forgotten.
- **What If: Select from Your Corpus**: Build it once, in your own words. Let AI choose the right stories for each job. Stay authentic.

---core-idea---
# "SELECT, don't COMPOSE"
Every resume bullet traces back to something you actually said. No hallucinated achievements. No fabricated metrics. Build your career corpus once — AI selects from it for each role.
- Your words, your corpus
- AI selects, never fabricates
- Human approves everything

---product-intro---
# Enter Job Journal
A corpus-driven, AI-native career management tool
- \`/interview\`: Build your career corpus conversationally
- \`/jobs\`: Discover and evaluate opportunities
- \`/apply\`: Score fit, generate tailored resumes, track everything
- \`/greenhouse\`: Monitor company job boards automatically
| 11,500 | lines of Python |
| 16 | database tables |
| 1 month | to build |

---demo-dashboard---
50+ applications across tabs, spreadsheets, and email. I couldn't keep it all in my head anymore.
Built a web dashboard powered by Claude Code + SQLite to see everything at a glance.
> Job Journal dashboard — pipeline status, scoring results, and application tracking

---demo-scoring---
Applying everywhere with no way to know which jobs actually fit before investing hours.
AI scores every job description against my corpus across 5 dimensions. Tells me to skip, consider, or go all-in — with reasoning.
> Scoring output — BigCommerce role scored 38/100 with recommendation to skip and detailed reasoning

---demo-resume---
Tailoring a resume meant 2-3 hours of copy-paste, reformatting, and second-guessing.
One command generates a tailored resume as a formatted Google Doc — selecting real achievements from my corpus. Never fabricated.
> Generated resume in Google Docs — formatted, tailored, and traceable to corpus entries

---demo-integrations---
Where is this job? Remote? Hybrid? And which of my 4 email threads has the latest status?
Google Maps API resolves company locations. Gmail integration pulls application confirmations and status updates automatically.
> Automated status updates pulled from Gmail — confirmations, interviews, and rejections

---demo-cli---
Sometimes you need to batch-process, automate, or debug. A GUI alone isn't enough.
30+ CLI commands for everything from corpus search to bulk scoring. Claude Code is the primary interface.
> Terminal session — corpus search, batch scoring, and application management via Claude Code

---meta---
The resume you reviewed was generated by this tool.
Job Journal wrote the resume. HoganOS presented the case study. Claude Code built them both.
Don Hogan | donhogan.com

---appendix-title---
# Technical Appendix
Architecture, principles, and trade-offs for the technically curious

---principles---
# Design Principles
- **Responsible AI**: Your words, your corpus. AI assists selection, not fabrication.
- **Strong Defaults**: One command to score a JD. One to generate a resume. Works out of the box.
- **User Control**: You review every bullet. You approve every resume. Human in the loop, always.

---architecture---
# System Architecture
Full lifecycle pipeline — not isolated features
Interview, Corpus, Discovery, Scoring, Generation, Tracking, Analytics
| 11,500 | Lines of Python |
| 16 | SQLite Tables |
| 13 | Modules |
| 4 | Integrations |

---tradeoffs---
# Durable Trade-offs
Every architecture decision is a bet on what matters
- **Local-first vs. Cloud** | Local-first | Career data is sensitive. 'Your data never leaves your machine' is a feature, not a limitation.
- **Corpus vs. AI-generated** | Corpus-backed | Traceability over convenience. Every bullet has a source. Hallucination rate: 0%.
- **CLI vs. GUI** | Both | Claude Code for conversations. CLI for automation. Web dashboard for visualization.
- **Optional deps vs. batteries-included** | Optional | Gmail, Google Docs, RAG install separately. Core works offline with zero config.

---numbers---
# By the Numbers
One month. One developer. One AI pair-programmer.
| 11,500 | lines of Python |
| 30+ | CLI commands |
| 16 | database tables |
| 4 | external integrations |
| 2,080 | lines of skill prompts |
| 1 | month to build |

---whats-next---
# What's Next
The architecture supports what hasn't been built yet
- **ATS Job Monitoring** [Designed]: Automatically poll Greenhouse, Lever, and Ashby boards for target companies. 277-line spec ready.
- **Bullet-level Selection** [Planned]: Choose specific achievements per role during resume generation. Infrastructure exists.
- **Open Source Release** [In Progress]: Community files, test suite, CI/CD pipeline. Local-first tools should be shared.
- **Platform for Others** [Vision]: The corpus architecture enables any corpus-driven career tool. Resume is just the first output.
`;

/* ------------------------------------------------------------------ */
/*  Section splitter                                                    */
/* ------------------------------------------------------------------ */

export function splitSections(markdown: string): Record<string, string> {
  const result: Record<string, string> = {};
  const parts = markdown.split(/^---(\S+)---$/m);

  // parts alternates: [preamble, id1, content1, id2, content2, ...]
  for (let i = 1; i < parts.length; i += 2) {
    const id = parts[i].trim();
    const content = (parts[i + 1] || '').trim();
    result[id] = content;
  }

  return result;
}

/* ------------------------------------------------------------------ */
/*  Text extractors                                                     */
/* ------------------------------------------------------------------ */

export function extractHeading(section: string): string {
  const m = section.match(/^# (.+)$/m);
  return m ? m[1] : '';
}

export function extractSubheading(section: string): string {
  const m = section.match(/^## (.+)$/m);
  return m ? m[1] : '';
}

export function extractBlockquote(section: string): string {
  const m = section.match(/^> (.+)$/m);
  return m ? m[1] : '';
}

export function extractItalic(section: string): string {
  const m = section.match(/^\*(.+)\*$/m);
  return m ? m[1] : '';
}

/** Lines starting with `- ` — returns raw line content after the dash */
export function extractListItems(section: string): string[] {
  const lines = section.split('\n');
  return lines
    .filter((l) => l.match(/^- /))
    .map((l) => l.replace(/^- /, '').trim());
}

/**
 * Parse a list item like `**Title**: Description` into { title, text }.
 * Falls back to full string as title if no bold found.
 */
export function parseListItem(item: string): { title: string; text: string } {
  const m = item.match(/^\*\*(.+?)\*\*[:\s]*(.*)$/);
  if (m) return { title: m[1], text: m[2] };
  return { title: item, text: '' };
}

/**
 * Parse a tradeoff item like `**Versus** | Decision | Why`
 */
export function parseTradeoffItem(item: string): {
  versus: string;
  decision: string;
  why: string;
} {
  const m = item.match(/^\*\*(.+?)\*\*\s*\|\s*(.+?)\s*\|\s*(.+)$/);
  if (m) return { versus: m[1], decision: m[2], why: m[3] };
  return { versus: item, decision: '', why: '' };
}

/**
 * Parse a roadmap item like `**Title** [Status]: Description`
 */
export function parseRoadmapItem(item: string): {
  title: string;
  status: string;
  desc: string;
} {
  const m = item.match(/^\*\*(.+?)\*\*\s*\[(.+?)\][:\s]*(.*)$/);
  if (m) return { title: m[1], status: m[2], desc: m[3] };
  return { title: item, status: '', desc: '' };
}

/**
 * Parse a workflow item like `` `/cmd`: Description ``
 */
export function parseWorkflowItem(item: string): {
  cmd: string;
  desc: string;
} {
  const m = item.match(/`(.+?)`[:\s]*(.+)$/);
  if (m) return { cmd: m[1], desc: m[2] };
  return { cmd: item, desc: '' };
}

/** Lines matching `| value | label |` */
export function extractTableRows(
  section: string,
): Array<{ value: string; label: string }> {
  const lines = section.split('\n');
  return lines
    .filter((l) => l.match(/^\|/))
    .map((l) => {
      const cells = l
        .split('|')
        .map((c) => c.trim())
        .filter(Boolean);
      return { value: cells[0] || '', label: cells[1] || '' };
    });
}

/**
 * Extract "plain" paragraphs — lines that are NOT headings, list items,
 * blockquotes, italic, or table rows.
 */
export function extractParagraphs(section: string): string[] {
  return section
    .split('\n')
    .filter(
      (l) =>
        l.trim() &&
        !l.match(/^#+ /) &&
        !l.match(/^- /) &&
        !l.match(/^> /) &&
        !l.match(/^\*.*\*$/) &&
        !l.match(/^\|/),
    )
    .map((l) => l.trim());
}

/**
 * Extract comma-separated items from a plain line (for cycle steps)
 */
export function extractCommaSeparated(section: string): string[] {
  const paragraphs = extractParagraphs(section);
  // Find the line with commas (the steps line)
  const stepsLine = paragraphs.find((p) => p.includes(','));
  if (!stepsLine) return [];
  return stepsLine.split(',').map((s) => s.trim());
}

/* ------------------------------------------------------------------ */
/*  localStorage read/write                                             */
/* ------------------------------------------------------------------ */

export function getStoredMarkdown(): string {
  if (typeof window === 'undefined') return defaultMarkdown;
  return localStorage.getItem(STORAGE_KEY) || defaultMarkdown;
}

export function setStoredMarkdown(markdown: string): void {
  if (typeof window === 'undefined') return;
  localStorage.setItem(STORAGE_KEY, markdown);
}

export function clearStoredMarkdown(): void {
  if (typeof window === 'undefined') return;
  localStorage.removeItem(STORAGE_KEY);
}
